artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/cf79001673fb4224a82b68bd4d96c373/artifacts
end_time: 1588800316303
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: cf79001673fb4224a82b68bd4d96c373
run_uuid: cf79001673fb4224a82b68bd4d96c373
source_name: ''
source_type: 4
source_version: ''
start_time: 1588800316145
status: 3
tags: []
user_id: root
