artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/44613222e33a43d99de63108ebfa4a03/artifacts
end_time: 1588445842665
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 44613222e33a43d99de63108ebfa4a03
run_uuid: 44613222e33a43d99de63108ebfa4a03
source_name: ''
source_type: 4
source_version: ''
start_time: 1588445842501
status: 3
tags: []
user_id: root
