artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/38e18e4de649466ab2dd93286ca24bc4/artifacts
end_time: 1588529630153
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 38e18e4de649466ab2dd93286ca24bc4
run_uuid: 38e18e4de649466ab2dd93286ca24bc4
source_name: ''
source_type: 4
source_version: ''
start_time: 1588529630003
status: 3
tags: []
user_id: root
