artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/f91fec01959a4b14b010d5cd26e30449/artifacts
end_time: 1588526678692
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f91fec01959a4b14b010d5cd26e30449
run_uuid: f91fec01959a4b14b010d5cd26e30449
source_name: ''
source_type: 4
source_version: ''
start_time: 1588526678536
status: 3
tags: []
user_id: root
