artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/e4c3dd33efb94e339325de3691510755/artifacts
end_time: 1588441456696
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e4c3dd33efb94e339325de3691510755
run_uuid: e4c3dd33efb94e339325de3691510755
source_name: ''
source_type: 4
source_version: ''
start_time: 1588441456543
status: 3
tags: []
user_id: root
