artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/f29798be1cbb4c6ab2c4beecc02f013d/artifacts
end_time: 1588434717107
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f29798be1cbb4c6ab2c4beecc02f013d
run_uuid: f29798be1cbb4c6ab2c4beecc02f013d
source_name: ''
source_type: 4
source_version: ''
start_time: 1588434716954
status: 3
tags: []
user_id: root
