artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/8e1b782d1a4b486f87babb94ad04f709/artifacts
end_time: 1588528572887
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8e1b782d1a4b486f87babb94ad04f709
run_uuid: 8e1b782d1a4b486f87babb94ad04f709
source_name: ''
source_type: 4
source_version: ''
start_time: 1588528572725
status: 3
tags: []
user_id: root
