artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/47503edd2a474ffa987c7e739fb47064/artifacts
end_time: 1588800871865
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 47503edd2a474ffa987c7e739fb47064
run_uuid: 47503edd2a474ffa987c7e739fb47064
source_name: ''
source_type: 4
source_version: ''
start_time: 1588800871695
status: 3
tags: []
user_id: root
