artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/fa9f5f55638848b79dc51f904f6b71a8/artifacts
end_time: 1588456364205
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fa9f5f55638848b79dc51f904f6b71a8
run_uuid: fa9f5f55638848b79dc51f904f6b71a8
source_name: ''
source_type: 4
source_version: ''
start_time: 1588456364044
status: 3
tags: []
user_id: root
