artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/c688ff391f1b4f248cf55196fd6f6eac/artifacts
end_time: 1588443172561
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c688ff391f1b4f248cf55196fd6f6eac
run_uuid: c688ff391f1b4f248cf55196fd6f6eac
source_name: ''
source_type: 4
source_version: ''
start_time: 1588443172399
status: 3
tags: []
user_id: root
