artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/e8eadf619362413ba7c80cff9abd9824/artifacts
end_time: 1588455432780
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e8eadf619362413ba7c80cff9abd9824
run_uuid: e8eadf619362413ba7c80cff9abd9824
source_name: ''
source_type: 4
source_version: ''
start_time: 1588455432619
status: 3
tags: []
user_id: root
