artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/aaed847e55264bae81277616a28f77a5/artifacts
end_time: 1588440976242
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: aaed847e55264bae81277616a28f77a5
run_uuid: aaed847e55264bae81277616a28f77a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1588440976086
status: 3
tags: []
user_id: root
