artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/68699022a02943e08db1fcd3b4ad3938/artifacts
end_time: 1588798930462
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 68699022a02943e08db1fcd3b4ad3938
run_uuid: 68699022a02943e08db1fcd3b4ad3938
source_name: ''
source_type: 4
source_version: ''
start_time: 1588798930306
status: 3
tags: []
user_id: root
