artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/01b44907d65e4c88a951baec4d1e48a5/artifacts
end_time: 1588799218116
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 01b44907d65e4c88a951baec4d1e48a5
run_uuid: 01b44907d65e4c88a951baec4d1e48a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1588799217970
status: 3
tags: []
user_id: root
