artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/c44543efe23b412abc9142b189001ddd/artifacts
end_time: 1588526908580
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c44543efe23b412abc9142b189001ddd
run_uuid: c44543efe23b412abc9142b189001ddd
source_name: ''
source_type: 4
source_version: ''
start_time: 1588526908398
status: 3
tags: []
user_id: root
