artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/462b686632d54aa380b27a0f82daf503/artifacts
end_time: 1588540102635
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 462b686632d54aa380b27a0f82daf503
run_uuid: 462b686632d54aa380b27a0f82daf503
source_name: ''
source_type: 4
source_version: ''
start_time: 1588540102470
status: 3
tags: []
user_id: root
