artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/131dabe2e3f14fc4b2543f7eeeb95cd7/artifacts
end_time: 1588505431641
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 131dabe2e3f14fc4b2543f7eeeb95cd7
run_uuid: 131dabe2e3f14fc4b2543f7eeeb95cd7
source_name: ''
source_type: 4
source_version: ''
start_time: 1588505431469
status: 3
tags: []
user_id: root
