artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/6a00a89ea32e45c09ef9dfcaa17c3271/artifacts
end_time: 1588799650617
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6a00a89ea32e45c09ef9dfcaa17c3271
run_uuid: 6a00a89ea32e45c09ef9dfcaa17c3271
source_name: ''
source_type: 4
source_version: ''
start_time: 1588799650462
status: 3
tags: []
user_id: root
