artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/2821cf68a7804f119bcb4c34cfce20a7/artifacts
end_time: 1588439936200
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2821cf68a7804f119bcb4c34cfce20a7
run_uuid: 2821cf68a7804f119bcb4c34cfce20a7
source_name: ''
source_type: 4
source_version: ''
start_time: 1588439936040
status: 3
tags: []
user_id: root
