artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/3fad8a558d7c425eb438682e8078eb5c/artifacts
end_time: 1588535453158
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3fad8a558d7c425eb438682e8078eb5c
run_uuid: 3fad8a558d7c425eb438682e8078eb5c
source_name: ''
source_type: 4
source_version: ''
start_time: 1588535453000
status: 3
tags: []
user_id: root
