artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/743cd7c12d974bc08e3b417bbb60fc69/artifacts
end_time: 1588533993875
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 743cd7c12d974bc08e3b417bbb60fc69
run_uuid: 743cd7c12d974bc08e3b417bbb60fc69
source_name: ''
source_type: 4
source_version: ''
start_time: 1588533993723
status: 3
tags: []
user_id: root
