artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/20eb902523c04edfbf8440d30f4c360d/artifacts
end_time: 1588525950077
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 20eb902523c04edfbf8440d30f4c360d
run_uuid: 20eb902523c04edfbf8440d30f4c360d
source_name: ''
source_type: 4
source_version: ''
start_time: 1588525949933
status: 3
tags: []
user_id: root
