artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/73b8a26602ee438197ffef56bda7d83a/artifacts
end_time: 1588800541326
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 73b8a26602ee438197ffef56bda7d83a
run_uuid: 73b8a26602ee438197ffef56bda7d83a
source_name: ''
source_type: 4
source_version: ''
start_time: 1588800541159
status: 3
tags: []
user_id: root
