artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/3c447eb4022b43d3bf50a0a7018a234f/artifacts
end_time: 1588527202203
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3c447eb4022b43d3bf50a0a7018a234f
run_uuid: 3c447eb4022b43d3bf50a0a7018a234f
source_name: ''
source_type: 4
source_version: ''
start_time: 1588527201668
status: 3
tags: []
user_id: root
