artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/d9d760aad66e41a484c40339cd4593cd/artifacts
end_time: 1588435973070
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: d9d760aad66e41a484c40339cd4593cd
run_uuid: d9d760aad66e41a484c40339cd4593cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1588435972918
status: 3
tags: []
user_id: root
