artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/cf9e37be152d48a58975fd5b1bb52366/artifacts
end_time: 1588430369151
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: cf9e37be152d48a58975fd5b1bb52366
run_uuid: cf9e37be152d48a58975fd5b1bb52366
source_name: ''
source_type: 4
source_version: ''
start_time: 1588430368997
status: 3
tags: []
user_id: root
