artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/200a93c562f94cf78a1bf792c3652ecd/artifacts
end_time: 1588799798164
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 200a93c562f94cf78a1bf792c3652ecd
run_uuid: 200a93c562f94cf78a1bf792c3652ecd
source_name: ''
source_type: 4
source_version: ''
start_time: 1588799797999
status: 3
tags: []
user_id: root
