artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/25556764b9574e9d883b2d43bfff0ba5/artifacts
end_time: 1588800070453
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 25556764b9574e9d883b2d43bfff0ba5
run_uuid: 25556764b9574e9d883b2d43bfff0ba5
source_name: ''
source_type: 4
source_version: ''
start_time: 1588800070298
status: 3
tags: []
user_id: root
