artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/a2d330b5c2424a66832dadc09a9889fc/artifacts
end_time: 1588527740914
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a2d330b5c2424a66832dadc09a9889fc
run_uuid: a2d330b5c2424a66832dadc09a9889fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1588527740764
status: 3
tags: []
user_id: root
