artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/53c5bd89f5bb48db9c27a1068be35d37/artifacts
end_time: 1588539974584
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 53c5bd89f5bb48db9c27a1068be35d37
run_uuid: 53c5bd89f5bb48db9c27a1068be35d37
source_name: ''
source_type: 4
source_version: ''
start_time: 1588539974424
status: 3
tags: []
user_id: root
