artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/a96e8ba6eda5423e9ee537ae8325c94a/artifacts
end_time: 1588428286784
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a96e8ba6eda5423e9ee537ae8325c94a
run_uuid: a96e8ba6eda5423e9ee537ae8325c94a
source_name: ''
source_type: 4
source_version: ''
start_time: 1588428286629
status: 3
tags: []
user_id: root
