artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/57c41c920a3c4ba48468f2304425c5ca/artifacts
end_time: 1588503854911
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 57c41c920a3c4ba48468f2304425c5ca
run_uuid: 57c41c920a3c4ba48468f2304425c5ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1588503854732
status: 3
tags: []
user_id: root
