artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/509435b0a9124eaa9c6519bdd1e18af2/artifacts
end_time: 1588464299004
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 509435b0a9124eaa9c6519bdd1e18af2
run_uuid: 509435b0a9124eaa9c6519bdd1e18af2
source_name: ''
source_type: 4
source_version: ''
start_time: 1588464298844
status: 3
tags: []
user_id: root
