artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/3625a97142de449c9e62b9a3a1f648dd/artifacts
end_time: 1588529856427
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3625a97142de449c9e62b9a3a1f648dd
run_uuid: 3625a97142de449c9e62b9a3a1f648dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1588529856232
status: 3
tags: []
user_id: root
