artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/4e713750b0da4fa79e9e43eb685269f9/artifacts
end_time: 1588538490561
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 4e713750b0da4fa79e9e43eb685269f9
run_uuid: 4e713750b0da4fa79e9e43eb685269f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1588538490390
status: 3
tags: []
user_id: root
