artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/75630838b66b4ccbb3c160ac57687b90/artifacts
end_time: 1588501254080
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 75630838b66b4ccbb3c160ac57687b90
run_uuid: 75630838b66b4ccbb3c160ac57687b90
source_name: ''
source_type: 4
source_version: ''
start_time: 1588501253909
status: 3
tags: []
user_id: root
