artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/5d39fed0a63340b5ad01d14c1a8f3270/artifacts
end_time: 1588429055850
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5d39fed0a63340b5ad01d14c1a8f3270
run_uuid: 5d39fed0a63340b5ad01d14c1a8f3270
source_name: ''
source_type: 4
source_version: ''
start_time: 1588429055698
status: 3
tags: []
user_id: root
