artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/15eb7507cbf6443e989e379ae624b2ca/artifacts
end_time: 1588454856965
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 15eb7507cbf6443e989e379ae624b2ca
run_uuid: 15eb7507cbf6443e989e379ae624b2ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1588454856809
status: 3
tags: []
user_id: root
