artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/24f8713afbd6443a855d7f10cf43bb91/artifacts
end_time: 1588449520429
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 24f8713afbd6443a855d7f10cf43bb91
run_uuid: 24f8713afbd6443a855d7f10cf43bb91
source_name: ''
source_type: 4
source_version: ''
start_time: 1588449520262
status: 3
tags: []
user_id: root
