artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/21b0465ebd364679bf3de41eacb81409/artifacts
end_time: 1588452097952
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 21b0465ebd364679bf3de41eacb81409
run_uuid: 21b0465ebd364679bf3de41eacb81409
source_name: ''
source_type: 4
source_version: ''
start_time: 1588452097794
status: 3
tags: []
user_id: root
