artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/823804bc8c52470e9d8a25977d200c0e/artifacts
end_time: 1588799073917
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 823804bc8c52470e9d8a25977d200c0e
run_uuid: 823804bc8c52470e9d8a25977d200c0e
source_name: ''
source_type: 4
source_version: ''
start_time: 1588799073771
status: 3
tags: []
user_id: root
