artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/a047f2036e9241e7afd84d6ea6a450f4/artifacts
end_time: 1588800652335
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a047f2036e9241e7afd84d6ea6a450f4
run_uuid: a047f2036e9241e7afd84d6ea6a450f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1588800652172
status: 3
tags: []
user_id: root
