artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/7e2f6421ba334152af8e90107c0dcfcc/artifacts
end_time: 1588449100296
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 7e2f6421ba334152af8e90107c0dcfcc
run_uuid: 7e2f6421ba334152af8e90107c0dcfcc
source_name: ''
source_type: 4
source_version: ''
start_time: 1588449100136
status: 3
tags: []
user_id: root
