artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/47f9a27152274bd6a0ba7e4d297a2df4/artifacts
end_time: 1588440484700
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 47f9a27152274bd6a0ba7e4d297a2df4
run_uuid: 47f9a27152274bd6a0ba7e4d297a2df4
source_name: ''
source_type: 4
source_version: ''
start_time: 1588440484541
status: 3
tags: []
user_id: root
