artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/e457d0c236be489caa1a99cda1d9d882/artifacts
end_time: 1588450934372
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e457d0c236be489caa1a99cda1d9d882
run_uuid: e457d0c236be489caa1a99cda1d9d882
source_name: ''
source_type: 4
source_version: ''
start_time: 1588450934206
status: 3
tags: []
user_id: root
