artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/98ce1f3e400c41e0b1a902658346f0a0/artifacts
end_time: 1588529399702
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 98ce1f3e400c41e0b1a902658346f0a0
run_uuid: 98ce1f3e400c41e0b1a902658346f0a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1588529399551
status: 3
tags: []
user_id: root
