artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/69a9f404ecf544ce9abc79ddd2050868/artifacts
end_time: 1588539611853
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 69a9f404ecf544ce9abc79ddd2050868
run_uuid: 69a9f404ecf544ce9abc79ddd2050868
source_name: ''
source_type: 4
source_version: ''
start_time: 1588539611665
status: 3
tags: []
user_id: root
