artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/8bbfdcec56e94a499c81e8a1a2703930/artifacts
end_time: 1588539308428
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8bbfdcec56e94a499c81e8a1a2703930
run_uuid: 8bbfdcec56e94a499c81e8a1a2703930
source_name: ''
source_type: 4
source_version: ''
start_time: 1588539308242
status: 3
tags: []
user_id: root
