artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/85a8ca62fbdc40c98743f5dc2709d45d/artifacts
end_time: 1588800764110
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 85a8ca62fbdc40c98743f5dc2709d45d
run_uuid: 85a8ca62fbdc40c98743f5dc2709d45d
source_name: ''
source_type: 4
source_version: ''
start_time: 1588800763959
status: 3
tags: []
user_id: root
