artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/pruning_mlflow/0/ea6eba7445ee4dbcae1f2c2d60ea5094/artifacts
end_time: 1588799507141
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ea6eba7445ee4dbcae1f2c2d60ea5094
run_uuid: ea6eba7445ee4dbcae1f2c2d60ea5094
source_name: ''
source_type: 4
source_version: ''
start_time: 1588799506968
status: 3
tags: []
user_id: root
