artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/0a51c1c3d1e94ccba576234bbc2ce159/artifacts
end_time: 1588459520336
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0a51c1c3d1e94ccba576234bbc2ce159
run_uuid: 0a51c1c3d1e94ccba576234bbc2ce159
source_name: ''
source_type: 4
source_version: ''
start_time: 1588459520173
status: 3
tags: []
user_id: root
