artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/e75d5c8d166c42109cbe385b4c9fd207/artifacts
end_time: 1588445171186
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e75d5c8d166c42109cbe385b4c9fd207
run_uuid: e75d5c8d166c42109cbe385b4c9fd207
source_name: ''
source_type: 4
source_version: ''
start_time: 1588445171032
status: 3
tags: []
user_id: root
