artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/8edb6ca6b0d24ce985a2f2297f1dba40/artifacts
end_time: 1588429497206
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8edb6ca6b0d24ce985a2f2297f1dba40
run_uuid: 8edb6ca6b0d24ce985a2f2297f1dba40
source_name: ''
source_type: 4
source_version: ''
start_time: 1588429497049
status: 3
tags: []
user_id: root
