artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns_2/0/cdba4b0521604cd3a275a427f2fd80e6/artifacts
end_time: 1588529174859
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: cdba4b0521604cd3a275a427f2fd80e6
run_uuid: cdba4b0521604cd3a275a427f2fd80e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1588529174704
status: 3
tags: []
user_id: root
