artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/dfd7d740ff444b508047f6efac9d6c1c/artifacts
end_time: 1588447987444
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dfd7d740ff444b508047f6efac9d6c1c
run_uuid: dfd7d740ff444b508047f6efac9d6c1c
source_name: ''
source_type: 4
source_version: ''
start_time: 1588447987259
status: 3
tags: []
user_id: root
