artifact_uri: file:///content/drive/My Drive/SysDL/Assg 3/mlruns/0/1934b27d60ca477baffccdbd0f38d2a4/artifacts
end_time: 1588458161632
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1934b27d60ca477baffccdbd0f38d2a4
run_uuid: 1934b27d60ca477baffccdbd0f38d2a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1588458161454
status: 3
tags: []
user_id: root
